---
- name: install nodejs
  apt:
    name: nodejs
    state: present
  become: yes

- name: install npm
  apt:
    name: npm
    state: present
  become: yes

- name: update npm
  shell: "npm i npm"

- name: set install path
  shell: "mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile"