---
- name: install nodejs
  apt:
    name: nodejs
    state: present
  become: yes

- name: install npm
  apt:
    name: npm
    state: present
  become: yes

- name: update npm
  shell: "npm i npm"

- name: create folder for npm globals
  shell: "mkdir /home/vagrant/.npm-global"

- name: set npm prefix
  shell: "npm config set prefix '/home/vagrant/.npm-global'"

- name: export Path with new npm globals dir
  shell: "export PATH=/home/vagrant/.npm-global/bin:$PATH"

- name: source profile
  shell: ". /home/vagrant/.profile"