---
- name: install nodejs
  apt:
    name: nodejs
    state: present
  become: yes

- name: install npm
  apt:
    name: npm
    state: present
  become: yes

- name: update npm
  shell: "npm i npm"

- name: create folder for npm globals
  shell: "mkdir -p /home/{{ ansible_user }}/.npm-global"

- name: set npm prefix
  shell: "npm config set prefix '/home/{{ ansible_user }}/.npm-global'"

- name: export path with new npm globals dir
  copy:
    dest: /etc/profile.d/npm-path.sh
    content: 'PATH=$PATH:/home/{{ ansible_user }}/.npm-global/bin'
  become: yes
